import sample from 'lodash-es/sample.js'
import { getInitialSettings } from '../utils/settings/settings.js'
import { getInteractiveLanguageTag } from '../utils/uiLanguage.js'

export function getSpinnerVerbs(): string[] {
  const settings = getInitialSettings()
  const config = settings.spinnerVerbs
  const defaults = getInteractiveLanguageTag() === 'zh' ? SPINNER_VERBS_ZH : SPINNER_VERBS

  if (!config) {
    return defaults
  }
  if (config.mode === 'replace') {
    return config.verbs.length > 0 ? config.verbs : defaults
  }
  return [...defaults, ...config.verbs]
}

export function isSpinnerVerbCompatibleWithLanguage(
  verb: string | undefined,
  languageTag = getInteractiveLanguageTag(),
): boolean {
  if (!verb) {
    return false
  }

  const hasHan = /[\p{Script=Han}\u3000-\u303f\uff00-\uffef]/u.test(verb)
  return languageTag === 'zh' ? hasHan : !hasHan
}

export function getSpinnerVerbForCurrentLanguage(verb?: string): string {
  if (isSpinnerVerbCompatibleWithLanguage(verb)) {
    return verb
  }

  return (
    sample(getSpinnerVerbs()) ??
    (getInteractiveLanguageTag() === 'zh' ? '处理中' : 'Working')
  )
}

// Spinner verbs for loading messages
export const SPINNER_VERBS = [
  'Accomplishing',
  'Actioning',
  'Actualizing',
  'Architecting',
  'Baking',
  'Beaming',
  "Beboppin'",
  'Befuddling',
  'Billowing',
  'Blanching',
  'Bloviating',
  'Boogieing',
  'Boondoggling',
  'Booping',
  'Bootstrapping',
  'Brewing',
  'Bunning',
  'Burrowing',
  'Calculating',
  'Canoodling',
  'Caramelizing',
  'Cascading',
  'Catapulting',
  'Cerebrating',
  'Channeling',
  'Channelling',
  'Choreographing',
  'Churning',
  'Coalescing',
  'Cogitating',
  'Combobulating',
  'Composing',
  'Computing',
  'Concocting',
  'Considering',
  'Contemplating',
  'Cooking',
  'Crafting',
  'Creating',
  'Crunching',
  'Crystallizing',
  'Cultivating',
  'Deciphering',
  'Deliberating',
  'Determining',
  'Dilly-dallying',
  'Discombobulating',
  'Doing',
  'Doodling',
  'Drizzling',
  'Ebbing',
  'Effecting',
  'Elucidating',
  'Embellishing',
  'Enchanting',
  'Envisioning',
  'Evaporating',
  'Fermenting',
  'Fiddle-faddling',
  'Finagling',
  'Flambéing',
  'Flibbertigibbeting',
  'Flowing',
  'Flummoxing',
  'Fluttering',
  'Forging',
  'Forming',
  'Frolicking',
  'Frosting',
  'Gallivanting',
  'Galloping',
  'Garnishing',
  'Generating',
  'Gesticulating',
  'Germinating',
  'Gitifying',
  'Grooving',
  'Gusting',
  'Harmonizing',
  'Hashing',
  'Hatching',
  'Herding',
  'Honking',
  'Hullaballooing',
  'Hyperspacing',
  'Ideating',
  'Imagining',
  'Improvising',
  'Incubating',
  'Inferring',
  'Infusing',
  'Ionizing',
  'Jitterbugging',
  'Julienning',
  'Kneading',
  'Leavening',
  'Levitating',
  'Manifesting',
  'Marinating',
  'Meandering',
  'Metamorphosing',
  'Misting',
  'Moonwalking',
  'Moseying',
  'Mulling',
  'Mustering',
  'Musing',
  'Nebulizing',
  'Nesting',
  'Newspapering',
  'Noodling',
  'Nucleating',
  'Orbiting',
  'Orchestrating',
  'Osmosing',
  'Perambulating',
  'Percolating',
  'Perusing',
  'Philosophising',
  'Photosynthesizing',
  'Pollinating',
  'Pondering',
  'Pontificating',
  'Pouncing',
  'Precipitating',
  'Prestidigitating',
  'Processing',
  'Proofing',
  'Propagating',
  'Puttering',
  'Puzzling',
  'Quantumizing',
  'Razzle-dazzling',
  'Razzmatazzing',
  'Recombobulating',
  'Reticulating',
  'Roosting',
  'Ruminating',
  'Sautéing',
  'Scampering',
  'Schlepping',
  'Scurrying',
  'Seasoning',
  'Shenaniganing',
  'Shimmying',
  'Simmering',
  'Skedaddling',
  'Sketching',
  'Slithering',
  'Smooshing',
  'Sock-hopping',
  'Spelunking',
  'Spinning',
  'Sprouting',
  'Stewing',
  'Sublimating',
  'Swirling',
  'Swooping',
  'Symbioting',
  'Synthesizing',
  'Tempering',
  'Thinking',
  'Thundering',
  'Tinkering',
  'Tomfoolering',
  'Topsy-turvying',
  'Transfiguring',
  'Transmuting',
  'Twisting',
  'Undulating',
  'Unfurling',
  'Unravelling',
  'Vibing',
  'Waddling',
  'Wandering',
  'Warping',
  'Whatchamacalliting',
  'Whirlpooling',
  'Whirring',
  'Whisking',
  'Wibbling',
  'Working',
  'Wrangling',
  'Zesting',
  'Zigzagging',
]

export const SPINNER_VERBS_ZH = [
  '处理中',
  '构思中',
  '分析中',
  '推演中',
  '梳理中',
  '规划中',
  '实现中',
  '编写中',
  '修改中',
  '重构中',
  '检查中',
  '排查中',
  '验证中',
  '调试中',
  '测试中',
  '整理中',
  '汇总中',
  '打磨中',
  '润色中',
  '联调中',
  '整合中',
  '对齐中',
  '回溯中',
  '定位中',
  '比对中',
  '推敲中',
  '准备中',
  '加载中',
  '思考中',
  '工作中',
  '编排中',
  '搭建中',
  '设计中',
  '布局中',
  '拆解中',
  '检索中',
  '查找中',
  '扫描中',
  '读取中',
  '解析中',
  '识别中',
  '计算中',
  '推导中',
  '求解中',
  '估算中',
  '研判中',
  '生成中',
  '起草中',
  '撰写中',
  '绘制中',
  '勾勒中',
  '转换中',
  '迁移中',
  '映射中',
  '转写中',
  '优化中',
  '精炼中',
  '压缩中',
  '提炼中',
  '收敛中',
  '编译中',
  '构建中',
  '打包中',
  '装配中',
  '清理中',
  '收尾中',
  '归档中',
  '提交中',
  '保存中',
  '学习中',
  '酝酿中',
  '揣摩中',
  '调度中',
  '协调中',
  '串联中',
  '分派中',
  '配齐中',
]
