//! Hook state management — translates React hooks into Rust state structs.
//!
//! Each `useXxx()` hook becomes a `struct XxxState` with fields representing
//! useState values and methods representing useCallback/useEffect logic.

#![allow(dead_code, unused_variables)]

pub mod notifs;
pub mod tool_permission;

mod after_first_render;
mod api_key_verification;
mod arrow_key_history;
mod assistant_history;
mod away_summary;
mod background_task_navigation;
mod blink;
mod can_use_tool;
mod cancel_request;
mod chrome_extension_notification;
mod clipboard_image_hint;
mod command_keybindings;
mod command_queue;
mod copy_on_select;
mod deferred_hook_messages;
mod diff_data;
mod diff_in_ide;
mod direct_connect;
mod double_press;
mod dynamic_config;
mod elapsed_time;
mod exit_on_ctrl_cd;
mod exit_on_ctrl_cd_with_keybindings;
mod file_history_snapshot_init;
mod file_suggestions;
mod global_keybindings;
mod history_search;
mod ide_at_mentioned;
mod ide_connection_status;
mod ide_integration;
mod ide_logging;
mod ide_selection;
mod inbox_poller;
mod input_buffer;
mod issue_flag_banner;
mod log_messages;
mod lsp_plugin_recommendation;
mod mailbox_bridge;
mod main_loop_model;
mod manage_plugins;
mod memory_usage;
mod merged_clients;
mod merged_commands;
mod merged_tools;
mod min_display_time;
mod mossen_hint_recommendation;
mod notify_after_timeout;
mod official_marketplace_notification;
mod paste_handler;
mod plugin_recommendation_base;
mod pr_status;
mod prompt_suggestion;
mod prompts_from_mossen_in_chrome;
mod queue_processor;
mod remote_session;
mod render_placeholder;
mod scheduled_tasks;
pub mod search_input;
mod session_backgrounding;
mod settings;
mod settings_change;
mod skill_improvement_survey;
mod skills_change;
mod ssh_session;
mod swarm_initialization;
mod swarm_permission_poller;
mod task_list_watcher;
mod tasks_v2;
mod teammate_view_auto_exit;
mod teleport_resume;
mod terminal_size;
mod text_input;
mod timeout;
mod turn_diffs;
mod typeahead;
mod unified_suggestions;
mod update_notification;
mod vim_input;
mod virtual_scroll;
mod voice;
mod voice_enabled;
mod voice_integration;

// Re-export primary types
pub use after_first_render::*;
pub use api_key_verification::*;
pub use arrow_key_history::*;
pub use assistant_history::*;
pub use away_summary::*;
pub use background_task_navigation::*;
pub use blink::*;
pub use can_use_tool::*;
pub use cancel_request::*;
pub use chrome_extension_notification::*;
pub use clipboard_image_hint::*;
pub use command_keybindings::*;
pub use command_queue::*;
pub use copy_on_select::*;
pub use deferred_hook_messages::*;
pub use diff_data::*;
pub use diff_in_ide::*;
pub use direct_connect::*;
pub use double_press::*;
pub use dynamic_config::*;
pub use elapsed_time::*;
pub use exit_on_ctrl_cd::*;
pub use exit_on_ctrl_cd_with_keybindings::*;
pub use file_history_snapshot_init::*;
pub use file_suggestions::*;
pub use global_keybindings::*;
pub use history_search::*;
pub use ide_at_mentioned::*;
pub use ide_connection_status::*;
pub use ide_integration::*;
pub use ide_logging::*;
pub use ide_selection::*;
pub use inbox_poller::*;
pub use input_buffer::*;
pub use issue_flag_banner::*;
pub use log_messages::*;
pub use lsp_plugin_recommendation::*;
pub use mailbox_bridge::*;
pub use main_loop_model::*;
pub use manage_plugins::*;
pub use memory_usage::*;
pub use merged_clients::*;
pub use merged_commands::*;
pub use merged_tools::*;
pub use min_display_time::*;
pub use mossen_hint_recommendation::*;
pub use notify_after_timeout::*;
pub use official_marketplace_notification::*;
pub use paste_handler::*;
pub use plugin_recommendation_base::*;
pub use pr_status::*;
pub use prompt_suggestion::*;
pub use prompts_from_mossen_in_chrome::*;
pub use queue_processor::*;
pub use remote_session::*;
pub use render_placeholder::*;
pub use scheduled_tasks::*;
pub use search_input::*;
pub use session_backgrounding::*;
pub use settings::*;
pub use settings_change::*;
pub use skill_improvement_survey::*;
pub use skills_change::*;
pub use ssh_session::*;
pub use swarm_initialization::*;
pub use swarm_permission_poller::*;
pub use task_list_watcher::*;
pub use tasks_v2::*;
pub use teammate_view_auto_exit::*;
pub use teleport_resume::*;
pub use terminal_size::*;
pub use text_input::*;
pub use timeout::*;
pub use turn_diffs::*;
pub use typeahead::*;
pub use unified_suggestions::*;
pub use update_notification::*;
pub use vim_input::*;
pub use virtual_scroll::*;
pub use voice::*;
pub use voice_enabled::*;
pub use voice_integration::*;
